"""Framework-agnostic core package for Slim Report Designer."""

__version__ = "0.6.0a0"

from .api import normalize_template, render_html, render_pdf
from .assets import (
    AssetError,
    AssetIdError,
    AssetNotFoundError,
    AssetPermissionError,
    AssetProvider,
    AssetStorageError,
    AssetTypeError,
    FileSystemAssetProvider,
    ImageSourceResolver,
    ResolvedImageSource,
    validate_asset_id,
)
from .builder import ObjectBuilder, PageBuilder, ReportBuilder, StyleBuilder
from .constants import DEFAULT_REPORT_VERSION
from .data import DataContext, DataProviderRegistry
from .data_sources import (
    CredentialResolver,
    DatasetField,
    DatasetSourceType,
    EnvironmentCredentialResolver,
    MySQLConnectionConfig,
    QueryParameter,
    ReportDataset,
    ReportDataSource,
)
from .events import EventDispatcher, EventListener, ReportEvent
from .exceptions import (
    CredentialResolutionError,
    DatasetValidationError,
    DataSourceError,
    DataSourceValidationError,
    ExporterError,
    ReportObjectNotFoundError,
    ReportSerializationError,
    ReportValidationError,
    SlimReportError,
    WidgetValidationError,
)
from .exporters import (
    BaseExporter,
    ExporterRegistry,
    HTMLExporter,
    PDFExporter,
    create_default_exporter_registry,
)
from .expressions import resolve_expression, resolve_text
from .models import (
    Asset,
    Band,
    BarcodeObject,
    Binding,
    FieldObject,
    ImageObject,
    Layer,
    LineObject,
    Margin,
    Metadata,
    Object,
    Page,
    Position,
    QRCodeObject,
    RectangleObject,
    ReportAsset,
    ReportBand,
    ReportMetadata,
    ReportObject,
    ReportPage,
    ReportTemplate,
    Size,
    Style,
    TableObject,
    TextObject,
)
from .object_factory import ObjectFactory
from .report import Report, ReportObjectCollection, create_default_template
from .serialization import BaseSerializer, JSONSerializer
from .validation import ReportValidationIssue, ReportValidationResult
from .widgets import (
    BaseWidget,
    FieldWidget,
    ImageWidget,
    LineWidget,
    RectangleWidget,
    TextWidget,
    WidgetRegistry,
    create_default_widget_registry,
)

__all__ = [
    "DEFAULT_REPORT_VERSION",
    "Asset",
    "AssetError",
    "AssetIdError",
    "AssetNotFoundError",
    "AssetPermissionError",
    "AssetProvider",
    "AssetStorageError",
    "AssetTypeError",
    "Band",
    "BarcodeObject",
    "BaseExporter",
    "BaseSerializer",
    "BaseWidget",
    "Binding",
    "CredentialResolutionError",
    "CredentialResolver",
    "DataContext",
    "DataProviderRegistry",
    "DataSourceError",
    "DataSourceValidationError",
    "DatasetField",
    "DatasetSourceType",
    "DatasetValidationError",
    "EnvironmentCredentialResolver",
    "EventDispatcher",
    "EventListener",
    "ExporterError",
    "ExporterRegistry",
    "FieldObject",
    "FieldWidget",
    "FileSystemAssetProvider",
    "HTMLExporter",
    "ImageObject",
    "ImageSourceResolver",
    "ImageWidget",
    "JSONSerializer",
    "Layer",
    "LineObject",
    "LineWidget",
    "Margin",
    "Metadata",
    "MySQLConnectionConfig",
    "Object",
    "ObjectBuilder",
    "ObjectFactory",
    "PDFExporter",
    "Page",
    "PageBuilder",
    "Position",
    "QRCodeObject",
    "QueryParameter",
    "RectangleObject",
    "RectangleWidget",
    "Report",
    "ReportAsset",
    "ReportBand",
    "ReportBuilder",
    "ReportDataSource",
    "ReportDataset",
    "ReportEvent",
    "ReportMetadata",
    "ReportObject",
    "ReportObjectCollection",
    "ReportObjectNotFoundError",
    "ReportPage",
    "ReportSerializationError",
    "ReportTemplate",
    "ReportValidationError",
    "ReportValidationIssue",
    "ReportValidationResult",
    "ResolvedImageSource",
    "Size",
    "SlimReportError",
    "Style",
    "StyleBuilder",
    "TableObject",
    "TextObject",
    "TextWidget",
    "WidgetRegistry",
    "WidgetValidationError",
    "create_default_exporter_registry",
    "create_default_template",
    "create_default_widget_registry",
    "normalize_template",
    "render_html",
    "render_pdf",
    "resolve_expression",
    "resolve_text",
    "validate_asset_id",
]
