"""Constants for Slim Report Designer core data structures."""

DEFAULT_REPORT_VERSION = "1.0"

DEFAULT_PAGE_WIDTH = 8.5
DEFAULT_PAGE_HEIGHT = 11.0
DEFAULT_PAGE_UNIT = "in"
DEFAULT_PAGE_ORIENTATION = "portrait"

DEFAULT_MARGIN_TOP = 0.5
DEFAULT_MARGIN_RIGHT = 0.5
DEFAULT_MARGIN_BOTTOM = 0.5
DEFAULT_MARGIN_LEFT = 0.5

